Restore sbt-cross Project setup
.. because I can't figure out why

    publishLocal in `scalafmt-api`

works, but

    publishLocal in `scalafmt-impl`

fails with

    error: overloaded method value in with alternatives:
      (scope: sbt.Scope)sbt.TaskKey[Unit] <and>
      (c: sbt.ConfigKey)sbt.TaskKey[Unit] <and>
      (t: sbt.Scoped)sbt.TaskKey[Unit] <and>
      (p: sbt.Reference)sbt.TaskKey[Unit]
     cannot be applied to (com.lucidchart.sbtcross.BaseProject)
          (publishLocal in `scalafmt-impl`).value
                        ^

¯\_(ツ)_/¯